changelog:
  categories:
    - title: Breaking Changes
      labels:
        - breaking-change
    - title: Features
      labels:
        - enhancement
        - feature
    - title: Fixes
      labels:
        - bug
        - bugfix
    - title: Maintenance
      labels:
        - chore
        - dependencies
        - documentation
  exclude:
    labels:
      - skip-changelog
