# This is a basic workflow to help you get started with Actions

name: Integration Tests

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  solution: 'WordPressPCL.sln'
  buildPlatform: Any CPU
  buildConfiguration: Release
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v1.9.0
      with:
        dotnet-version: 6.0.x
    - name: Build Solution
      run: dotnet build ${{ env.solution }} -c Release
      
    - name: Create dockerzied WordPress
      run: docker-compose -f ./dev/docker-compose.yml up

    - name: Check Docker
      run: |
        docker ps
        curl --fail http://localhost:8080
        sleep 10s
    
    - name: 'Run Tests: Selfhosted WordPress with JWT-AUTH'
      run: dotnet test -l "console;verbosity=detailed" WordPressPCL.Tests.Selfhosted/WordPressPCL.Tests.Selfhosted.csproj -s WordPressPCL.Tests.Selfhosted/jwtauth.runsettings
